import type { Metadata } from 'next'
import StyledComponentsRegistry from '@/lib/style/registry'
import { GlobalStyle } from '@/lib/style/globalStyles'
import RecoilRootWrapper from '@/lib/recoil/recoilWrapper'
import React from 'react'
import ThemeWrapper from '@/lib/style/theme/themeWrapper'
import { LocalFonts } from '@/lib/style/localFonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StyledComponentsRegistry>
      <GlobalStyle />
      <ThemeWrapper>
        <html lang="ko">
          <body className={LocalFonts.SUITv1.className}>
            <RecoilRootWrapper>{children}</RecoilRootWrapper>
          </body>
        </html>
      </ThemeWrapper>
    </StyledComponentsRegistry>
  )
}
