import type { Metadata } from 'next'
import StyledComponentsRegistry from '@/lib/style/registry'
import { GlobalStyle } from '@/lib/style/globalStyles'
import RecoilRootWrapper from '@/lib/recoil/recoilWrapper'
import React from 'react'
import ThemeWrapper from '@/lib/style/theme/themeWrapper'
import { LocalFonts } from '@/lib/style/localFonts'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import Header from '@/lib/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <StyledComponentsRegistry>
      <GlobalStyle />
      <ThemeWrapper>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <html lang={locale}>
            <body className={locale === 'ja' ? LocalFonts.NotoSansJP.className : LocalFonts.SUITv1.className}>
              <RecoilRootWrapper>
                <Header />
                {children}
              </RecoilRootWrapper>
            </body>
          </html>
        </NextIntlClientProvider>
      </ThemeWrapper>
    </StyledComponentsRegistry>
  )
}
